### ISSUE TITLE
Write instructions on how to make changes to the website

### ISSUE THREAD

**Issue by MagicMilly** [az-digitalag/group-website#1]
- Clone to local machine
- Instructions for creating a branch and for forking your own repo
- How to make changes locally and then create PR for review
- How to stay updated with master / pull changes
- either in README.md or CONTRIBUTING.md

**Comment by KristinaRiemer** [comment]
I've been putting these in [az-digitalag/organization](https://github.com/az-digitalag/organization/issues) so they show up on ZenHub, but maybe we want to add this repo to ZenHub?

**Comment by MagicMilly** [comment]
Forgot about how adding extra repos makes ZenHub slower. I'll close this and open a new issue in that one!
